### ISSUE TITLE
Changes to the project config are not possible while in read-only mode

### ISSUE THREAD

**Issue by stenvdb** [ethercreative/mailchimp-commerce#12]
I'm getting this error thrown when installing the plugin through project.yml changes. It looks like something that has been discussed a couple of times here https://github.com/nystudio107/craft-seomatic/issues/365, https://github.com/craftcms/cms/issues/4101 and https://github.com/craftcms/cms/issues/3653

The exact error I get back through the command line is:
`Installing plugin "mailchimp-commerce" ... error: Changes to the project config are not possible while in read-only mode.`

**Comment by Tam** [comment]
This is a Craft issue, none of our code touches project config.

**Comment by stenvdb** [comment]
Very strange, you're right. 

After uninstalling mailchimp-commerce, deploying again on our live env, then installing it again and deploying again it went though just fine. Seems like a recurring bug in Craft with multiple possible causes. Not this plugin's fault.
