### ISSUE TITLE
Twig variables for data sync?

### ISSUE THREAD

**Issue by ghost** [ethercreative/mailchimp-commerce#22]
We have a complex site with a lot of api fetching that we are using from twig variables, like description, thumb and pictures for products.

Is it possible to make a choice in the dropdown that parses/handles twig variables, like the SEOmatic plugin or in some fields in the admin panel?

Here is an example from the use in SEOmatic:
`{{ craft.pluginhandle.apifield(object.product.id).description ?? '' }}`

**Comment by erlendsr** [comment]
This option would be super nice to have. Anything we could do to make this happen?
