### ISSUE TITLE
Invalid email on order causes sync process to halt

### ISSUE THREAD

**Issue by peteeveleigh** [ethercreative/mailchimp-commerce#24]
Have just diagnosed a syncing issue when trying to sync orders to Mailchimp. A number of orders would sync but then an error was thrown. Looking at the logs showed that Mailchimp didn't like the email address.

After a bit of trouble tracking down which order was the problem I found that an order had an incorrect email address (used .con instead of .com).

This address was refused by Mailchimp which caused the plugin to halt the entire sync process.

Would be good if the the plugin could skip past the errors (after logging them with a bit more detail) and continue with the syncing process.

**Comment by alexjcollins** [comment]
@fantasticmachine Thanks for bringing this up. Definitely on board with your suggestion. We'll discuss further internally and hopefully get something rolled out soon-ish.

**Comment by peteeveleigh** [comment]
@alexjcollins Thanks
Just adding the order id into the error message logged in line 144 or OrdersService.php would be super helpful for people trying to diagnose problems.
