### ISSUE TITLE
Composer install issue

### ISSUE THREAD

**Issue by 3dgroup** [ethercreative/mailchimp-commerce#34]
Get the following error when trying to push to live server:

Deprecation Notice: Class ether\mc\base\MailchimpProduct located in ./vendor/ether/mailchimp-commerce/src/base/MailChimpProduct.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///opt/sp/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201
Deprecation Notice: Class HTMLPurifier_Language_en_x_test located in ./vendor/ezyang/htmlpurifier/library/HTMLPurifier/Language/classes/en-x-test.php does not comply with psr-0 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///opt/sp/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by knynkwl** [comment]
Any update on this?

**Comment by 3dgroup** [comment]
> Any update on this?

From memory I contact craft support about this, there was a pending Craft CMS update. After updating this error went away.

**Comment by alexjcollins** [comment]
@3dgroup Thanks for providing a response on this, really appreciated.

@knynkwl Let us know if you can't resolve the issue following @3dgroup 's feedback and sorry for not getting back to you sooner.

**Comment by 3dgroup** [comment]
@alexjcollins Sorry, just checked. I couldn't use this plugin because of this error. I have just attempted to use it again and it fails. No setting pages appear on live or staging to sync any products so i can only assume the plugin doesn't install. The error that appears:

Deprecation Notice: Class ether\mc\base\MailchimpProduct located in ./vendor/ether/mailchimp-commerce/src/base/MailChimpProduct.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in phar:///opt/sp/bin/composer.phar/src/Composer/Autoload/ClassMapGenerator.php:201

**Comment by christopherhealey** [comment]
Brandon Kelly posted an issue with a solution to this. I also can not use this plugin anymore, will have to switch to another if this isn't resolved soon.
