### ISSUE TITLE
[Feature request/question] Cron URL

### ISSUE THREAD

**Issue by 23d1** [ethercreative/mailchimp-commerce#4]
Is there a possibility to access a url pattern (with perhaps a secret key in the url) to run the abandoned cart check/send?

**Comment by Tam** [comment]
The plugin doesn't handle whether a cart is abandoned or not, that's down to your settings in Mailchimp. For example, if you specified 1 hour in your campaign then Mailchimp will send the email 1 hour after the last update to the cart it recieved. We queue the updates so you might want to run the `./craft queue/run` command on a cron for faster syncing with Mailchimp if you have lots of other tasks running.
