### ISSUE TITLE
Syncing products: failed

### ISSUE THREAD

**Issue by nilsenpaul** [ethercreative/mailchimp-commerce#5]
When trying to sync products to Mailchimp, the job fails. This is what the queue.log says:

`{"type":"http://developer.mailchimp.com/documentation/mailchimp/guides/error-glossary/","title":"Resource Not Found","status":404,"detail":"The requested resource could not be found.","instance":"deada5a7-1384-421f-840a-348459e26102"}`

After a bit of debugging, I can see the correct product data being sent to Mailchimp in a post request.

The customer has a free account (it's not upgraded yet), could that be the problem. Do Mailchimp's Commerce features require a paid account?

**Comment by alexjcollins** [comment]
Hey, thanks for taking the time to dig into things a bit a bit further. Did the queue log happen to have anything else plugin related? Maybe any prior successful requests?

As for the account, you’re able to run transactional emails on the free plan so you’re all good there 👍

**Comment by nilsenpaul** [comment]
All plugin related log entries are product sync fails. They all have a different instance ID.
I was able to sync the store, and I do have a `storeId` (checked by logging it).

**Comment by Tam** [comment]
@nilsenpaul Mailchimp requires a valid store address, which we previously weren't catching the error for. So while it looks like your store has synced, it actually hasn't.

I've just pushed a release that handles this correctly. You'll want to go to the settings section, disconnect your site, then reconnect it and it should be fixed.

**Comment by nilsenpaul** [comment]
@Tam It works now! I have a new issue with order syncing, but I will post that as a new issue. You can close this one!
